### ISSUE TITLE
No constructor found

### ISSUE THREAD

**Issue by TomWu370** [codingsnack/leetcode-api#1]
when trying the tutorial line, const lc = new Leetcode({ csrfToken, leetcodeSession });
Following error is thrown, Type 'typeof import("F:/Pycharm/project/leetcodegacha/node_modules/@codingsnack/leetcode-api/lib/index")' has no construct signatures

**Comment by rohitkrishna094** [comment]
Hey sorry about that, you need to actually import the library to use it. I have updated the readme with proper code. Try that it should work now.

**Comment by rohitkrishna094** [comment]
Hi I am closing this issue. You can reopen or just comment here in case you face any other problems. Thanks
