### ISSUE TITLE
Leetcode-api 0.0.3 - npm package is blank

### ISSUE THREAD

**Issue by CormacOBroin** [codingsnack/leetcode-api#2]
When you downgrade to 0.0.2, it starts to be usable, however; it doesn't seem to take in parameters effectively. When using the latest version, the node_modules folder for this project is blank

**Comment by rohitkrishna094** [comment]
Thanks for posting this issue. Not sure how 0.0.3 got published, but I have unpublished failing versions. Now you can use the latest version(just do `npm i @codingsnack/leetcode-api` and it should download the 0.0.5 version which is the latest as of now).

**Comment by CormacOBroin** [comment]
Excellent! Thanks Rohit!
